version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password  
  web:
    build: .
    command: bundle exec rackup --port 1234 --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "1234:1234"
    depends_on:
      - db